# Generated by Django 6.0.6 on 2026-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="expiration de l'abonnement"),
        ),
    ]
