# Generated by Django 6.0.6 on 2026-09-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_user_plan_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Bienvenue'), ('purchase_success', 'Achat réussi'), ('purchase_failed', 'Achat échoué'), ('payment_pending', 'Paiement en attente'), ('download_limit_warning', 'Quota téléchargement'), ('plan_activated', 'Plan activé'), ('contribution_submitted', 'Contribution reçue'), ('contribution_approved', 'Contribution publiée'), ('contribution_rejected', 'Contribution refusée'), ('contributor_earning', 'Gain contributeur'), ('payout_paid', 'Retrait versé'), ('payout_rejected', 'Retrait refusé'), ('system', 'Système')], default='system', max_length=30),
        ),
    ]
