# Generated by Django 6.0.6 on 2026-09-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text="Date d'acceptation des conditions d'utilisation et de la politique de confidentialité.", null=True, verbose_name='conditions acceptées le'),
        ),
    ]
