# Generated by Django 6.0.6 on 2026-06-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], max_length=10)),
                ('category', models.CharField(choices=[('paysages', 'Paysages'), ('nature', 'Nature & fleuves'), ('culture', 'Culture & traditions'), ('events', 'Événements'), ('archi', 'Architecture')], max_length=20)),
                ('format', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('file_key', models.CharField(help_text='Clé Cloudflare R2', max_length=500, unique=True)),
                ('file_url', models.URLField(blank=True, max_length=1000)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('resolution', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='Prix payé en FCFA')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('max_downloads', models.PositiveIntegerField(default=1)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='media_app.media')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
