# Generated by Django 6.0.6 on 2026-06-23 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchased_at'], 'verbose_name': 'Achat', 'verbose_name_plural': 'Achats'},
        ),
        migrations.RemoveField(
            model_name='media',
            name='file_key',
        ),
        migrations.RemoveField(
            model_name='media',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='media',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='media',
            name='format',
        ),
        migrations.RemoveField(
            model_name='media',
            name='is_published',
        ),
        migrations.AddField(
            model_name='media',
            name='altitude',
            field=models.FloatField(blank=True, help_text='Altitude du drone en mètres', null=True, verbose_name='Altitude (m)'),
        ),
        migrations.AddField(
            model_name='media',
            name='aperture',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ouverture'),
        ),
        migrations.AddField(
            model_name='media',
            name='bitrate',
            field=models.CharField(blank=True, help_text='Ex: 50 Mbps', max_length=30, verbose_name='Bitrate'),
        ),
        migrations.AddField(
            model_name='media',
            name='camera_model',
            field=models.CharField(blank=True, default='DJI Mavic 3 Pro', max_length=100, verbose_name='Modèle caméra/drone'),
        ),
        migrations.AddField(
            model_name='media',
            name='capture_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de capture'),
        ),
        migrations.AddField(
            model_name='media',
            name='capture_time',
            field=models.TimeField(blank=True, help_text='Golden hour, lever/coucher de soleil...', null=True, verbose_name='Heure de capture'),
        ),
        migrations.AddField(
            model_name='media',
            name='city',
            field=models.CharField(blank=True, help_text='Ex: Libreville, Port-Gentil', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='media',
            name='codec',
            field=models.CharField(blank=True, help_text='Ex: H.264, H.265, VP9', max_length=50, verbose_name='Codec'),
        ),
        migrations.AddField(
            model_name='media',
            name='color_profile',
            field=models.CharField(blank=True, default='sRGB', max_length=50, verbose_name='Profil couleur'),
        ),
        migrations.AddField(
            model_name='media',
            name='country',
            field=models.CharField(default='Gabon', max_length=50, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du média', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, help_text='Image (jpg, png, webp, avif) ou Vidéo (mp4, webm, mov) — Stocké sur Cloudflare R2', null=True, upload_to='media/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'mp4', 'webm', 'mov'])], verbose_name='Fichier média'),
        ),
        migrations.AddField(
            model_name='media',
            name='focal_length',
            field=models.CharField(blank=True, max_length=20, verbose_name='Focale'),
        ),
        migrations.AddField(
            model_name='media',
            name='frame_rate',
            field=models.CharField(blank=True, help_text='Ex: 30fps, 60fps', max_length=10, verbose_name='Images/seconde'),
        ),
        migrations.AddField(
            model_name='media',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hauteur (px)'),
        ),
        migrations.AddField(
            model_name='media',
            name='iso',
            field=models.CharField(blank=True, max_length=10, verbose_name='ISO'),
        ),
        migrations.AddField(
            model_name='media',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='media',
            name='lens',
            field=models.CharField(blank=True, max_length=100, verbose_name='Objectif'),
        ),
        migrations.AddField(
            model_name='media',
            name='license_type',
            field=models.CharField(default='Commerciale · Illimitée', help_text="Type de licence accordée à l'acheteur", max_length=50, verbose_name='Licence'),
        ),
        migrations.AddField(
            model_name='media',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='media',
            name='province',
            field=models.CharField(blank=True, help_text='Estuaire, Haut-Ogooué, Ogooué-Maritime, etc.', max_length=50, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='media',
            name='rating',
            field=models.FloatField(default=0, help_text='Sur 5 étoiles', verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='media',
            name='season',
            field=models.CharField(blank=True, max_length=50, verbose_name='Saison'),
        ),
        migrations.AddField(
            model_name='media',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=20, verbose_name="Vitesse d'obturation"),
        ),
        migrations.AddField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=15, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.CharField(blank=True, help_text='Séparés par des virgules', max_length=500, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Miniature pour les vidéos (optionnel pour les photos)', null=True, upload_to='thumbnails/%Y/%m/', verbose_name='Miniature'),
        ),
        migrations.AddField(
            model_name='media',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Vues'),
        ),
        migrations.AddField(
            model_name='media',
            name='weather',
            field=models.CharField(blank=True, help_text='Ex: Ensoleillé, Nuageux, Pluvieux', max_length=100, verbose_name='Météo'),
        ),
        migrations.AddField(
            model_name='media',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Largeur (px)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('paysages', 'Paysages'), ('nature', 'Nature & fleuves'), ('culture', 'Culture & traditions'), ('events', 'Événements'), ('archi', 'Architecture')], max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='media',
            name='downloads',
            field=models.PositiveIntegerField(default=0, verbose_name='Téléchargements'),
        ),
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.CharField(blank=True, help_text='Ex: 0:30 ou 1:00', max_length=20, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='media',
            name='price',
            field=models.PositiveIntegerField(default=1500, help_text='Prix de vente en FCFA', verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='resolution',
            field=models.CharField(blank=True, help_text='Ex: 8 000 × 5 333 px, 6 000 × 4 000 px', max_length=50, verbose_name='Résolution'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='media',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nb téléchargements'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='max_downloads',
            field=models.PositiveIntegerField(default=1, verbose_name='Max téléchargements'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Prix payé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Acheté le'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['type', 'category'], name='media_app_m_type_e379e2_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['status'], name='media_app_m_status_32d626_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['-created_at'], name='media_app_m_created_02e439_idx'),
        ),
    ]
