# Generated by Django 6.0.6 on 2026-06-23 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_alter_purchase_options_remove_media_file_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='altitude',
            field=models.FloatField(blank=True, help_text='Altitude du drone au moment de la capture, en mètres (ex: 120 pour la limite légale au Gabon).', null=True, verbose_name='Altitude drone (m)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='aperture',
            field=models.CharField(blank=True, help_text="Ouverture du diaphragme (ex: 'f/2.8', 'f/5.6'). Affecte la profondeur de champ et la luminosité.", max_length=10, verbose_name='Ouverture'),
        ),
        migrations.AlterField(
            model_name='media',
            name='bitrate',
            field=models.CharField(blank=True, help_text='Débit vidéo : 50 Mbps pour la 4K standard, 100 Mbps pour la 4K haute qualité.', max_length=30, verbose_name='Bitrate'),
        ),
        migrations.AlterField(
            model_name='media',
            name='camera_model',
            field=models.CharField(blank=True, default='DJI Mavic 3 Pro', help_text='Modèle de drone ou appareil photo utilisé. Ex: DJI Mavic 3 Pro, DJI Air 3, Sony A7R V.', max_length=100, verbose_name='Drone / Caméra'),
        ),
        migrations.AlterField(
            model_name='media',
            name='capture_date',
            field=models.DateField(blank=True, help_text='Date à laquelle la photo/vidéo a été prise (JJ/MM/AAAA).', null=True, verbose_name='Date de capture'),
        ),
        migrations.AlterField(
            model_name='media',
            name='capture_time',
            field=models.TimeField(blank=True, help_text='Heure de la prise de vue. Important pour les photos de golden hour (lever/coucher du soleil).', null=True, verbose_name='Heure de capture'),
        ),
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('paysages', 'Paysages'), ('nature', 'Nature & fleuves'), ('culture', 'Culture & traditions'), ('events', 'Événements'), ('archi', 'Architecture')], help_text='Catégorie principale du média pour le classement et les filtres sur la plateforme.', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='media',
            name='city',
            field=models.CharField(blank=True, help_text='Ville ou localité la plus proche du lieu de prise de vue (ex: Libreville, Port-Gentil, Franceville).', max_length=100, verbose_name='Ville / Localité'),
        ),
        migrations.AlterField(
            model_name='media',
            name='codec',
            field=models.CharField(blank=True, help_text='Format de compression : H.264 (compatible partout), H.265/HEVC (meilleure compression), VP9 (web).', max_length=50, verbose_name='Codec vidéo'),
        ),
        migrations.AlterField(
            model_name='media',
            name='color_profile',
            field=models.CharField(blank=True, default='sRGB', help_text="Espace colorimétrique de l'image. sRGB pour le web, Adobe RGB ou DCI-P3 pour l'impression.", max_length=50, verbose_name='Profil couleur'),
        ),
        migrations.AlterField(
            model_name='media',
            name='country',
            field=models.CharField(default='Gabon', help_text='Pays où la prise de vue a été réalisée.', max_length=50, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, help_text="Description détaillée visible sur la page du média. Décrivez le lieu, l'ambiance, les conditions de prise de vue.", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.CharField(blank=True, help_text="Durée de la vidéo au format '0:30' (30 secondes) ou '1:00' (1 minute).", max_length=20, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, help_text='Sélectionnez le fichier image ou vidéo. Stockage automatique sur Cloudflare R2. Formats acceptés : JPG, PNG, WebP, AVIF, MP4, WebM, MOV.', null=True, upload_to='media/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'mp4', 'webm', 'mov'])], verbose_name='Fichier média'),
        ),
        migrations.AlterField(
            model_name='media',
            name='focal_length',
            field=models.CharField(blank=True, help_text="Longueur focale en mm (ex: '24mm', '70mm'). Influence le champ de vision et la compression de la perspective.", max_length=20, verbose_name='Focale'),
        ),
        migrations.AlterField(
            model_name='media',
            name='frame_rate',
            field=models.CharField(blank=True, help_text="Fréquence d'images : 24fps (cinéma), 30fps (standard), 60fps (fluide).", max_length=10, verbose_name='Images par seconde'),
        ),
        migrations.AlterField(
            model_name='media',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text="Hauteur de l'image en pixels (ex: 5333 pour une photo 4K).", null=True, verbose_name='Hauteur (px)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='iso',
            field=models.CharField(blank=True, help_text="Sensibilité du capteur (ex: '100', '400', '800'). ISO bas = moins de bruit, ISO élevé = faible luminosité.", max_length=10, verbose_name='Sensibilité ISO'),
        ),
        migrations.AlterField(
            model_name='media',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordonnée GPS de latitude (ex: 0.4162 pour Libreville).', null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='media',
            name='lens',
            field=models.CharField(blank=True, help_text="Objectif utilisé. Pour un drone : 'Hasselblad 24mm f/2.8'. Pour un appareil photo : '24-70mm f/2.8'.", max_length=100, verbose_name='Objectif'),
        ),
        migrations.AlterField(
            model_name='media',
            name='license_type',
            field=models.CharField(default='Commerciale · Illimitée', help_text="Droits accordés à l'acheteur. Par défaut : licence commerciale illimitée (usage web, print, publicité).", max_length=50, verbose_name='Type de licence'),
        ),
        migrations.AlterField(
            model_name='media',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordonnée GPS de longitude (ex: 9.4673 pour Libreville).', null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='media',
            name='price',
            field=models.PositiveIntegerField(default=1500, help_text='Prix de vente en Francs CFA. Tarifs recommandés : Photo HD = 1 500 FCFA, Photo 4K = 3 000 FCFA, Vidéo 30s = 5 000 FCFA, Vidéo 1min = 10 000 FCFA.', verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='province',
            field=models.CharField(blank=True, help_text='Province du Gabon : Estuaire, Haut-Ogooué, Moyen-Ogooué, Ngounié, Nyanga, Ogooué-Ivindo, Ogooué-Lolo, Ogooué-Maritime, Woleu-Ntem.', max_length=50, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='media',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Note moyenne'),
        ),
        migrations.AlterField(
            model_name='media',
            name='resolution',
            field=models.CharField(blank=True, help_text="Format d'affichage : '8 000 × 5 333 px' pour la 4K, '6 000 × 4 000 px' pour la HD.", max_length=50, verbose_name='Résolution'),
        ),
        migrations.AlterField(
            model_name='media',
            name='season',
            field=models.CharField(blank=True, help_text='Saison de la prise de vue : Saison des pluies (oct-mai), Saison sèche (juin-sept).', max_length=50, verbose_name='Saison'),
        ),
        migrations.AlterField(
            model_name='media',
            name='shutter_speed',
            field=models.CharField(blank=True, help_text="Temps d'exposition (ex: '1/1000s', '1/60s'). Rapide pour figer le mouvement, lent pour les filés.", max_length=20, verbose_name="Vitesse d'obturation"),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', help_text='Brouillon : invisible sur le site. Publié : visible et achetable. Archivé : masqué mais conservé.', max_length=15, verbose_name='Statut de publication'),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags séparés par des virgules. Ex: drone, paysage, coucher de soleil, estuaire, gabon. Améliorent la recherche.', max_length=500, verbose_name='Mots-clés'),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="Image d'aperçu affichée dans les grilles et listes. Pour les vidéos, choisissez une image représentative. Format recommandé : 16/9.", null=True, upload_to='thumbnails/%Y/%m/', verbose_name='Miniature'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(help_text="Nom du média tel qu'affiché sur la plateforme. Soyez descriptif (ex: 'Coucher de soleil sur l'Estuaire — Libreville')", max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], help_text='Photo : image fixe (JPEG, PNG, WebP, AVIF). Vidéo : séquence animée (MP4, WebM, MOV).', max_length=10, verbose_name='Type de média'),
        ),
        migrations.AlterField(
            model_name='media',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='media',
            name='weather',
            field=models.CharField(blank=True, help_text='Météo lors de la capture : Ensoleillé, Nuageux, Pluvieux, Orageux, Brumeux.', max_length=100, verbose_name='Conditions météo'),
        ),
        migrations.AlterField(
            model_name='media',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text="Largeur de l'image en pixels (ex: 8000 pour une photo 4K).", null=True, verbose_name='Largeur (px)'),
        ),
    ]
