# Generated by Django 6.0.6 on 2026-06-23 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_alter_media_altitude_alter_media_aperture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('paysages', 'Paysages'), ('nature', 'Nature & fleuves'), ('foret', 'Forêt équatoriale'), ('mer', 'Mer & Océan'), ('lac', 'Lac & Lagune'), ('riviere', 'Rivière & Fleuve'), ('village', 'Village traditionnel'), ('ville', 'Ville & Architecture'), ('culture', 'Culture & traditions'), ('events', 'Événements'), ('archi', 'Architecture moderne'), ('faune', 'Faune sauvage'), ('flore', 'Flore & Végétation'), ('aerial', 'Vue aérienne'), ('nocturne', 'Vue nocturne'), ('coucher', 'Coucher de soleil')], help_text='Catégorie principale du média pour le classement et les filtres sur la plateforme.', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='media',
            name='price',
            field=models.PositiveIntegerField(default=1500, help_text='Prix minimum : 500 FCFA. Tarifs recommandés : Photo HD 1 500, Photo 4K 3 000, Vidéo 30s 5 000, Vidéo 1min 10 000.', validators=[django.core.validators.MinValueValidator(500, 'Le prix minimum est de 500 FCFA.')], verbose_name='Prix (FCFA)'),
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], max_length=10, verbose_name='Type de média')),
                ('quality', models.CharField(help_text='Ex: HD, 4K, 30s, 1min, RAW', max_length=20, verbose_name='Qualité')),
                ('price', models.PositiveIntegerField(help_text='Prix minimum : 500 FCFA', validators=[django.core.validators.MinValueValidator(500)], verbose_name='Prix (FCFA)')),
                ('description', models.CharField(blank=True, help_text='Description affichée sur la grille tarifaire', max_length=255, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)", verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Configuration de prix',
                'verbose_name_plural': 'Configurations de prix',
                'ordering': ['media_type', 'order'],
                'unique_together': {('media_type', 'quality')},
            },
        ),
    ]
