# Generated by Django 6.0.6 on 2026-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0005_alter_media_category_alter_media_price_pricingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='quality',
            field=models.CharField(choices=[('720', '720p'), ('1080', '1080p'), ('HD', 'HD'), ('4K', '4K')], default='HD', help_text='Qualité du média : 720p, 1080p, HD ou 4K.', max_length=10, verbose_name='Qualité'),
        ),
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('paysages', 'Paysages'), ('nature', 'Nature & fleuves'), ('foret', 'Forêt équatoriale'), ('mer', 'Mer & Océan'), ('lac', 'Lac & Lagune'), ('riviere', 'Rivière & Fleuve'), ('village', 'Village traditionnel'), ('ville', 'Ville & Architecture'), ('culture', 'Culture & traditions'), ('events', 'Événements'), ('archi', 'Architecture moderne'), ('faune', 'Faune sauvage'), ('flore', 'Flore & Végétation'), ('aerial', 'Vue aérienne'), ('nocturne', 'Vue nocturne'), ('coucher', 'Coucher de soleil')], help_text='Catégorie principale pour le classement et les filtres.', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée visible sur la page du média.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', help_text='Brouillon : invisible. Publié : visible et achetable. Archivé : masqué mais conservé.', max_length=15, verbose_name='Statut de publication'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(help_text="Nom du média tel qu'affiché sur la plateforme. Soyez descriptif.", max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], help_text='Photo : image fixe. Vidéo : séquence animée.', max_length=10, verbose_name='Type de média'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='quality',
            field=models.CharField(choices=[('720', '720p'), ('1080', '1080p'), ('HD', 'HD'), ('4K', '4K')], help_text='720p, 1080p, HD ou 4K', max_length=20, verbose_name='Qualité'),
        ),
    ]
