# Generated by Django 6.0.6 on 2026-06-23 19:05

import django.core.validators
import media_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0006_media_quality_alter_media_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, help_text='Sélectionnez le fichier image ou vidéo. Stockage automatique sur Cloudflare R2. Formats acceptés : JPG, PNG, WebP, AVIF, MP4, WebM, MOV.', null=True, upload_to=media_app.models.media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'mp4', 'webm', 'mov'])], verbose_name='Fichier média'),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="Image d'aperçu affichée dans les grilles et listes. Pour les vidéos, choisissez une image représentative. Format recommandé : 16/9.", null=True, upload_to=media_app.models.media_upload_path, verbose_name='Miniature'),
        ),
    ]
