# Generated by Django 6.0.6 on 2026-06-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0007_alter_media_file_alter_media_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('method', models.CharField(choices=[('Airtel Money', 'Airtel Money'), ('Moov Money', 'Moov Money'), ('Visa', 'Visa'), ('Mastercard', 'Mastercard')], max_length=20, verbose_name='Méthode')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Référence')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('status', models.CharField(choices=[('success', 'Réussi'), ('simulated', 'Simulé'), ('failed', 'Échoué')], default='success', max_length=15, verbose_name='Statut')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='ID Transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Paiement reçu',
                'verbose_name_plural': 'Paiements reçus',
                'ordering': ['-created_at'],
            },
        ),
    ]
