# Generated by Django 6.0.6 on 2026-06-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0008_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Référence transaction'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(blank=True, default='success', max_length=15, verbose_name='Statut du paiement'),
        ),
    ]
