# Generated by Django 6.0.5 on 2026-07-04 13:07

import media_app.models
from django.db import migrations, models

LEGACY_CATEGORIES = [
    ("paysages", "Paysages"),
    ("nature", "Nature & fleuves"),
    ("foret", "Forêt équatoriale"),
    ("mer", "Mer & Océan"),
    ("lac", "Lac & Lagune"),
    ("riviere", "Rivière & Fleuve"),
    ("village", "Village traditionnel"),
    ("ville", "Ville & Architecture"),
    ("culture", "Culture & traditions"),
    ("events", "Événements"),
    ("archi", "Architecture moderne"),
    ("faune", "Faune sauvage"),
    ("flore", "Flore & Végétation"),
    ("aerial", "Vue aérienne"),
    ("nocturne", "Vue nocturne"),
    ("coucher", "Coucher de soleil"),
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("media_app", "Category")
    for order, (slug, name) in enumerate(LEGACY_CATEGORIES):
        Category.objects.get_or_create(slug=slug, defaults={"name": name, "order": order})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0011_medialike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(help_text="Utilisé dans les filtres et l'API. Sans espace ni accent (ex: nature, paysages).", max_length=30, unique=True, verbose_name='Identifiant (slug)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, help_text='Décochez pour masquer cette catégorie des filtres sans supprimer les médias associés.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='medialike',
            new_name='media_app_m_media_i_69a5d6_idx',
            old_name='media_app_m_media_i_8f3a21_idx',
        ),
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(choices=media_app.models.Category.choices, help_text='Catégorie principale pour le classement et les filtres. Gérées dans « Catégories ».', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'En attente'), ('success', 'Réussi'), ('simulated', 'Simulé'), ('failed', 'Échoué')], default='success', max_length=15, verbose_name='Statut du paiement'),
        ),
        migrations.RunPython(seed_categories, reverse_code=noop),
    ]
