# Generated by Django 6.0.5 on 2026-07-04 13:49

import django.core.validators
import media_app.models
from django.db import migrations, models

LEGACY_QUALITIES = [
    ("HD", "HD"),
    ("4K", "4K"),
]

# Tarifs par défaut si aucune configuration n'existe déjà pour cette combinaison
DEFAULT_PRICING = [
    ("photo", "HD", 750, 0),
    ("photo", "4K", 1250, 1),
    ("video", "HD", 2000, 2),
    ("video", "4K", 3000, 3),
]


def seed_qualities_and_pricing(apps, schema_editor):
    Quality = apps.get_model("media_app", "Quality")
    Media = apps.get_model("media_app", "Media")
    PricingConfig = apps.get_model("media_app", "PricingConfig")

    for order, (slug, name) in enumerate(LEGACY_QUALITIES):
        Quality.objects.get_or_create(slug=slug, defaults={"name": name, "order": order})

    # Les résolutions 720p/1080p sont désormais regroupées sous "HD"
    Media.objects.filter(quality__in=["720", "1080"]).update(quality="HD")

    for media_type, quality, price, order in DEFAULT_PRICING:
        PricingConfig.objects.get_or_create(
            media_type=media_type, quality=quality,
            defaults={"price": price, "order": order},
        )

    # Applique le tarif configuré à tous les médias existants
    prices = {(c.media_type, c.quality): c.price for c in PricingConfig.objects.filter(is_active=True)}
    for media in Media.objects.all():
        price = prices.get((media.type, media.quality))
        if price is not None and media.price != price:
            media.price = price
            media.save(update_fields=["price"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0012_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('slug', models.SlugField(help_text="Valeur exacte utilisée en base et dans l'API (ex: HD, 4K, 8K). Respectez la casse.", max_length=10, unique=True, verbose_name='Code technique')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, help_text='Décochez pour masquer cette qualité des filtres et des tarifs sans supprimer les médias associés.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
            ],
            options={
                'verbose_name': 'Qualité',
                'verbose_name_plural': 'Qualités',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='media',
            name='price',
            field=models.PositiveIntegerField(default=1500, help_text="Calculé automatiquement depuis la configuration de prix (type + qualité). Modifiable uniquement s'il n'existe aucune configuration pour cette combinaison.", validators=[django.core.validators.MinValueValidator(500, 'Le prix minimum est de 500 FCFA.')], verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='quality',
            field=models.CharField(choices=media_app.models.Quality.choices, default='HD', help_text='Qualité du média. Gérée dans « Qualités ». Détermine le prix (voir Paiements → Configurations de prix).', max_length=10, verbose_name='Qualité'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='quality',
            field=models.CharField(choices=media_app.models.Quality.choices, help_text='Qualité concernée par ce tarif. Gérée dans « Qualités ».', max_length=10, verbose_name='Qualité'),
        ),
        migrations.RunPython(seed_qualities_and_pricing, reverse_code=noop),
    ]
