# Generated by Django 6.0.5 on 2026-07-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0013_quality_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='license_type',
            field=models.CharField(choices=[('Commerciale · Illimitée', "Commerciale · Illimitée (web, print, publicité — sans limite d'usage)"), ('Usage web uniquement', 'Usage web uniquement (sites internet, réseaux sociaux, newsletters)'), ('Usage éditorial', 'Usage éditorial (presse, actualités — usage non commercial)'), ('Usage personnel', 'Usage personnel (usage privé, non commercial, non revendable)'), ('Exclusive', 'Exclusive (droits exclusifs, média retiré du catalogue public après achat)')], default='Commerciale · Illimitée', help_text="Droits accordés à l'acheteur. Par défaut : licence commerciale illimitée (usage web, print, publicité).", max_length=50, verbose_name='Type de licence'),
        ),
    ]
