# Generated by Django 6.0.6 on 2026-09-23 13:07

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0016_generalize_payment_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='customer_account_number',
            field=models.CharField(blank=True, default='', max_length=23, verbose_name='Téléphone client'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Raison de l'échec"),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Frais'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='pvit_transaction_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID transaction MyPVit'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='raw_create_response',
            field=models.JSONField(blank=True, default=dict, verbose_name="Réponse d'initiation"),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='raw_webhook_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dernier webhook'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='redirect_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL formulaire carte'),
        ),
        migrations.AlterField(
            model_name='media',
            name='price',
            field=models.PositiveIntegerField(default=1500, help_text="Calculé automatiquement depuis la configuration de prix (type + qualité). Modifiable uniquement s'il n'existe aucune configuration pour cette combinaison.", validators=[django.core.validators.MinValueValidator(100, 'Le prix minimum est de 100 FCFA.')], verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='provider',
            field=models.CharField(choices=[('mypvit', 'MyPVit'), ('fedapay', 'FedaPay (ancien)'), ('singpay', 'SingPay (ancien)')], default='mypvit', max_length=20, verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='price',
            field=models.PositiveIntegerField(help_text='Prix minimum : 100 FCFA', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Prix (FCFA)'),
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['status', 'created_at'], name='media_app_p_status_aff042_idx'),
        ),
    ]
