# Generated by Django 6.0.6 on 2026-09-23 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0017_mypvit_payment_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='buyout_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Rachat direct : laissé vide, il est calculé depuis les tarifs de rachat selon la qualité retenue.', null=True, verbose_name='Montant du rachat (FCFA)'),
        ),
        migrations.AddField(
            model_name='media',
            name='contributor',
            field=models.ForeignKey(blank=True, help_text='Vide pour un média de la plateforme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Contributeur'),
        ),
        migrations.AddField(
            model_name='media',
            name='contributor_price',
            field=models.PositiveIntegerField(blank=True, help_text='Utilisé comme prix de vente en mode « partage des ventes ».', null=True, verbose_name='Prix fixé par le contributeur (FCFA)'),
        ),
        migrations.AddField(
            model_name='media',
            name='declared_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée déclarée (s)'),
        ),
        migrations.AddField(
            model_name='media',
            name='payout_mode',
            field=models.CharField(blank=True, choices=[('revenue_share', 'Partage des ventes'), ('buyout', 'Rachat direct')], help_text='Partage : le contributeur touche un pourcentage de chaque vente. Rachat : il est payé une fois, à la validation, et le média devient celui de la plateforme.', max_length=20, verbose_name='Rémunération choisie'),
        ),
        migrations.AddField(
            model_name='media',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Communiqué au contributeur si le média est refusé.', verbose_name='Motif du refus'),
        ),
        migrations.AddField(
            model_name='media',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Examiné le'),
        ),
        migrations.AddField(
            model_name='media',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par'),
        ),
        migrations.AddField(
            model_name='media',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Soumis le'),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('published', 'Publié'), ('rejected', 'Refusé'), ('archived', 'Archivé')], default='draft', help_text='Brouillon : invisible. Publié : visible et achetable. Archivé : masqué mais conservé.', max_length=15, verbose_name='Statut de publication'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['contributor', 'status'], name='media_app_m_contrib_f20f15_idx'),
        ),
    ]
