# Generated by Django 6.0.6 on 2026-09-23 18:23

import media_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0018_media_buyout_amount_media_contributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='preview',
            field=models.ImageField(blank=True, editable=False, help_text="Généré automatiquement depuis l'original : c'est la seule image d'une photo servie au public.", null=True, upload_to=media_app.models.preview_upload_path, verbose_name='Aperçu public filigrané'),
        ),
        migrations.AddField(
            model_name='media',
            name='preview_source',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
