# Generated by Django 6.0.6 on 2026-09-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0019_media_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='Taille du fichier (octets)'),
        ),
    ]
