# Generated by Django 6.0.6 on 2026-09-23 15:34

import django.core.validators
import django.db.models.deletion
import media_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_app', '0018_media_buyout_amount_media_contributor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepting_submissions', models.BooleanField(default=True, help_text="Décochez pour suspendre temporairement l'envoi de nouveaux médias.", verbose_name='Soumissions ouvertes')),
                ('commission_percent', models.PositiveSmallIntegerField(default=30, help_text="Prélevée sur chaque vente d'un média en « partage des ventes ». Le contributeur touche le reste.", validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Part de la plateforme (%)')),
                ('min_price', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Prix minimum fixé par un contributeur (FCFA)')),
                ('max_price', models.PositiveIntegerField(default=100000, verbose_name='Prix maximum fixé par un contributeur (FCFA)')),
                ('max_video_seconds', models.PositiveIntegerField(default=90, help_text='1 min 30 s = 90 secondes.', verbose_name="Durée maximale d'une vidéo (secondes)")),
                ('max_photo_size_mb', models.PositiveIntegerField(default=25, verbose_name="Taille maximale d'une photo (Mo)")),
                ('max_video_size_mb', models.PositiveIntegerField(default=500, verbose_name="Taille maximale d'une vidéo (Mo)")),
                ('min_payout', models.PositiveIntegerField(default=1000, verbose_name='Retrait minimum (FCFA)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réglages contributeurs',
                'verbose_name_plural': 'Réglages contributeurs',
            },
        ),
        migrations.CreateModel(
            name='BuyoutRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], max_length=10, verbose_name='Type de média')),
                ('quality', models.CharField(choices=media_app.models.Quality.choices, max_length=10, verbose_name='Qualité')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant du rachat (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Tarif de rachat',
                'verbose_name_plural': 'Tarifs de rachat',
                'ordering': ['media_type', '-amount'],
                'unique_together': {('media_type', 'quality')},
            },
        ),
        migrations.CreateModel(
            name='ContributorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Affiché sur les médias publiés (« par … »).', max_length=80, verbose_name='Nom affiché')),
                ('bio', models.TextField(blank=True, max_length=600, verbose_name='Présentation')),
                ('payout_operator', models.CharField(blank=True, choices=[('Airtel Money', 'Airtel Money'), ('Moov Money', 'Moov Money')], max_length=20, verbose_name='Opérateur Mobile Money')),
                ('payout_phone', models.CharField(blank=True, help_text='Numéro qui reçoit les retraits (format 077000000).', max_length=12, verbose_name='Numéro Mobile Money')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu')], default='active', help_text='Un contributeur suspendu ne peut plus soumettre de média ni demander de retrait.', max_length=12, verbose_name='Statut')),
                ('terms_accepted_at', models.DateTimeField(verbose_name='Charte acceptée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contributeur',
                'verbose_name_plural': 'Contributeurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant demandé (FCFA)')),
                ('operator', models.CharField(max_length=20, verbose_name='Opérateur')),
                ('phone', models.CharField(max_length=12, verbose_name='Numéro Mobile Money')),
                ('status', models.CharField(choices=[('requested', 'À traiter'), ('paid', 'Versé'), ('rejected', 'Refusé')], default='requested', max_length=12, verbose_name='Statut')),
                ('transaction_reference', models.CharField(blank=True, help_text='Obligatoire pour marquer la demande comme versée.', max_length=100, verbose_name='Référence du transfert')),
                ('admin_note', models.CharField(blank=True, max_length=255, verbose_name='Note (visible par le contributeur)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'verbose_name_plural': 'Demandes de retrait',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributorEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sale_share', "Part d'une vente"), ('buyout', 'Rachat direct'), ('adjustment', 'Ajustement manuel')], max_length=20, verbose_name='Type')),
                ('gross_amount', models.PositiveIntegerField(help_text='Prix de vente (partage) ou montant du rachat.', verbose_name='Montant de base (FCFA)')),
                ('commission_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Part plateforme appliquée (%)')),
                ('amount', models.IntegerField(verbose_name='Gain du contributeur (FCFA)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributor_earnings', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor_earnings', to='media_app.media')),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor_earning', to='media_app.purchase')),
            ],
            options={
                'verbose_name': 'Gain contributeur',
                'verbose_name_plural': 'Gains contributeurs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'buyout')), fields=('media',), name='unique_buyout_per_media')],
            },
        ),
    ]
