# Generated by Django 6.0.6 on 2026-09-23 15:58

import contributors.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_seed_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='proof',
            field=models.FileField(blank=True, help_text='Capture ou reçu du transfert Mobile Money (JPG, PNG, WebP ou PDF, 10 Mo maximum). Le contributeur peut la consulter depuis son espace.', upload_to=contributors.models.payout_proof_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf'])], verbose_name='Preuve de paiement'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Preuve ajoutée le'),
        ),
    ]
